server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: false #不需要进行注册
feign:
  hystrix:
    enabled: true