server:
  port: 7002
eureka:
  instance:
    hostname: server3   #eureka服务器实例名称
  client:
    register-with-eureka: false   #是否注册自己
    fetch-registry: false  #表示自己就是注册中心不需要检测自己
    service-url:
      defaultZone: https://server1:7000/eureka,https://server2:7001/eureka #指定客户端访问eureka服务器的地址

