server:
  port: 9002
spring:
  application:
    name: zuul9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
zuul:
  routes:
    clond.serviceId: provider8083
    clond.Path: /clond/**
#    配置关闭原始服务路径
  ignored-services:
   - provider8083
  prefix: /good
#  上面配置前缀，通过zuul去访问必须加前缀